### ISSUE TITLE
Issues with Marktioneer

### ISSUE THREAD

**Issue by CooLowbro** [fiote/ToS-Addons#16]
- It doesnt allow to place an item under the undercut limit. IMC removed the limit, so doesnt make sense keeping this feature beacause you can sell any item for any price. (This problem I could solve myself removing 4 lines)

- It crashes when read gems or items like mallardu meat

- It doesnt read reciepes from the market.

**Comment by fiote** [comment]
Hi @CooLowbro, thanks for creating this issue. 
Sadly, I don't play anymore, so I can't really correct this. Feel free to do a pull-request with those fixes :)

**Comment by CooLowbro** [comment]
Hello @fiote! Unfortunately I'm not a programmer. Just an analyst. But if I make any considerable progress, I will make a pull request. Thanks for all!
