### ISSUE TITLE
Marktioneer

### ISSUE THREAD

**Issue by bsides** [fiote/ToS-Addons#17]
You think you can release its source? Couldn't find it. In fact I'm only interessed because I'd like it to save the prices in a file (could be json) since the market bugs every day. It would be nice for a price check.

Thank you!

**Comment by fiote** [comment]
The source can already be found on https://github.com/fiote/ToS-Addons/tree/master/cwmarket.

**Comment by bsides** [comment]
Thank you @fiote, since the names were different I didn't notice it. Do you have any plans to save the prices in a file so we could have a hint of how much the item is worth without having to rescan the market everytime we quit the game? Thank you again.

**Comment by fiote** [comment]
I don't play ToS anymore, and so I don't work on any of my addons. Feel free to change it yourself and send a pull request if you want to :)

**Comment by bsides** [comment]
@fiote thanks, I'm learning how to do that based on how you read and write json in cwFarmed. I remember there were a Discord server where people talked about addon development for ToS, is that still on? If so, could you invite me? I'm kind of lost in Lua and how some things work here. Thank you again and sorry for the trouble.

**Comment by bsides** [comment]
One more thing... I decrypted marktioneer and compared cwMarket and they are not the same addon.

**Comment by fiote** [comment]
Sorry about that then. I don't have the sources files anymore, but I'm glad you managed to get them by decrypting the IPF :)

About the discord, I'm long gone from anything related to ToS, so I can't stay if that's still running. Sorry!
