### ISSUE TITLE
Marktioneer gerando saidas para planilha.

### ISSUE THREAD

**Issue by YuudaiNoboru** [fiote/ToS-Addons#18]
Bom dia Fiote,

Primeiramente dou um grande fã e utilizador de seu addons para o TOS. Gostaria de perdi sua ajuda, sou um comerciante no TOS, vivo comprando e vendendo itens, seu addon Marktioneer me ajuda muito nesse negocio, mais gostaria muito de algo que pudesse geral uma planilha do excel com todos os preços de todos os itens do mercado, assim como o Marktioneer lê todos os preços e salva nos itens, então pensei que uma adaptação no Marktioneer poderia fazer isso. Você acha que isso é possível ? Ler todos os itens e preços do mercado e jogar automaticamente para uma planilha ? Isso me ajudaria muito em meus comércios. Muito obrigado por todo seu trabalho no TOS.

**Comment by fiote** [comment]
@Malakia007 , eu não jogo mais TOS e não faço mais nada nos addons. Infelizmente não posso te ajudar nessa! Foi mal :\
