### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ztin** [fiote/ToS-Addons#2]
just update today and no longer see 2 buttons on the market anymore sad !!

**Comment by fiote** [comment]
Weird! I'll take a look later today.

**Comment by smileness** [comment]
Hello,
Error report, after latest update, cw Addons not loaded anymore :(

Are u stopping sharing this addons ? :)

Hope you can take a look and see if you an fix it.

Thanks

Best Regards

Smile~~

**Comment by fiote** [comment]
cxMarket fixed. Please download the newest version using the addon manager.

**Comment by ztin** [comment]
thanks :D
