### ISSUE TITLE
cwFarmed addon - request

### ISSUE THREAD

**Issue by sweepberry** [fiote/ToS-Addons#3]
Hi, can I ask if it's possible to separate the "loot" findings posted on chat from other sources? (shout,msg,normal). Maybe, set a separate or aligned 'tab' special for it like those of shout, All, normal, etc. or act like one of them.
As of now the options were to put it on/off. 
My issue is, I still want to check them but in a manner of not flooding the other pages.
so here's what I think would look like: (L for loot)
![image](https://cloud.githubusercontent.com/assets/19995193/16151814/872f916a-34d1-11e6-977f-38f9f957e695.png)
Note: maybe a /farmed chat on/off?
Sorry for this I used Ms paint.
Hope you get the idea. Thank you.

**Comment by murilobaixou** [comment]
Hi @sweepberry! I'm not really looking for messing the chat tabs. I may, in the future, create a floating frame to log that individually. Not sure though. Thanks for the suggestion!

**Comment by fiote** [comment]
Hi @sweepberry! I'm not really looking for messing the chat tabs. I may, in the future, create a floating frame to log that individually. Not sure about it, though. Sorry if that's annoying you =\
